select count(*) as 'Rows' from [UmdHealthCentre.Prescribed];
select count(*) as 'Rows' from [UmdHealthCentre.Doctor];
select count(*) as 'Rows' from [UmdHealthCentre.PatientRecord];
select count(*) as 'Rows' from [UmdHealthCentre.ParticipatesIn];
select count(*) as 'Rows' from [UmdHealthCentre.Medicine];
select count(*) as 'Rows' from [UmdHealthCentre.Treatment];
select count(*) as 'Rows' from [UmdHealthCentre.Treats];
select count(*) as 'Rows' from [UmdHealthCentre.StudentDB];
select count(*) as 'Rows' from [UmdHealthCentre.Insurance]
